
package br.com.fiap3esr.stubclasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "DivisionService", targetNamespace = "http://service.fiap3esr.com.br/", wsdlLocation = "http://localhost:8080/calculadora/division?wsdl")
public class DivisionService
    extends Service
{

    private static final URL DIVISIONSERVICE_WSDL_LOCATION;
    private static final WebServiceException DIVISIONSERVICE_EXCEPTION;
    private static final QName DIVISIONSERVICE_QNAME = new QName("http://service.fiap3esr.com.br/", "DivisionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/calculadora/division?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DIVISIONSERVICE_WSDL_LOCATION = url;
        DIVISIONSERVICE_EXCEPTION = e;
    }

    public DivisionService() {
        super(__getWsdlLocation(), DIVISIONSERVICE_QNAME);
    }

    public DivisionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DIVISIONSERVICE_QNAME, features);
    }

    public DivisionService(URL wsdlLocation) {
        super(wsdlLocation, DIVISIONSERVICE_QNAME);
    }

    public DivisionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DIVISIONSERVICE_QNAME, features);
    }

    public DivisionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DivisionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Operation
     */
    @WebEndpoint(name = "DivisionPort")
    public Operation getDivisionPort() {
        return super.getPort(new QName("http://service.fiap3esr.com.br/", "DivisionPort"), Operation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Operation
     */
    @WebEndpoint(name = "DivisionPort")
    public Operation getDivisionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.fiap3esr.com.br/", "DivisionPort"), Operation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DIVISIONSERVICE_EXCEPTION!= null) {
            throw DIVISIONSERVICE_EXCEPTION;
        }
        return DIVISIONSERVICE_WSDL_LOCATION;
    }

}
