
package br.com.fiap3esr.stubclasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "MultiplicationService", targetNamespace = "http://service.fiap3esr.com.br/", wsdlLocation = "http://localhost:8080/calculadora/multiplication?wsdl")
public class MultiplicationService
    extends Service
{

    private static final URL MULTIPLICATIONSERVICE_WSDL_LOCATION;
    private static final WebServiceException MULTIPLICATIONSERVICE_EXCEPTION;
    private static final QName MULTIPLICATIONSERVICE_QNAME = new QName("http://service.fiap3esr.com.br/", "MultiplicationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/calculadora/multiplication?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MULTIPLICATIONSERVICE_WSDL_LOCATION = url;
        MULTIPLICATIONSERVICE_EXCEPTION = e;
    }

    public MultiplicationService() {
        super(__getWsdlLocation(), MULTIPLICATIONSERVICE_QNAME);
    }

    public MultiplicationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MULTIPLICATIONSERVICE_QNAME, features);
    }

    public MultiplicationService(URL wsdlLocation) {
        super(wsdlLocation, MULTIPLICATIONSERVICE_QNAME);
    }

    public MultiplicationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MULTIPLICATIONSERVICE_QNAME, features);
    }

    public MultiplicationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MultiplicationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Operation
     */
    @WebEndpoint(name = "MultiplicationPort")
    public Operation getMultiplicationPort() {
        return super.getPort(new QName("http://service.fiap3esr.com.br/", "MultiplicationPort"), Operation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Operation
     */
    @WebEndpoint(name = "MultiplicationPort")
    public Operation getMultiplicationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.fiap3esr.com.br/", "MultiplicationPort"), Operation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MULTIPLICATIONSERVICE_EXCEPTION!= null) {
            throw MULTIPLICATIONSERVICE_EXCEPTION;
        }
        return MULTIPLICATIONSERVICE_WSDL_LOCATION;
    }

}
