
package br.com.fiap3esr.stubclasses;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Operation", targetNamespace = "http://service.fiap3esr.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Operation {


    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showResult", targetNamespace = "http://service.fiap3esr.com.br/", className = "br.com.fiap3esr.stubclasses.ShowResult")
    @ResponseWrapper(localName = "showResultResponse", targetNamespace = "http://service.fiap3esr.com.br/", className = "br.com.fiap3esr.stubclasses.ShowResultResponse")
    @Action(input = "http://service.fiap3esr.com.br/Operation/showResultRequest", output = "http://service.fiap3esr.com.br/Operation/showResultResponse")
    public String showResult(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showName", targetNamespace = "http://service.fiap3esr.com.br/", className = "br.com.fiap3esr.stubclasses.ShowName")
    @ResponseWrapper(localName = "showNameResponse", targetNamespace = "http://service.fiap3esr.com.br/", className = "br.com.fiap3esr.stubclasses.ShowNameResponse")
    @Action(input = "http://service.fiap3esr.com.br/Operation/showNameRequest", output = "http://service.fiap3esr.com.br/Operation/showNameResponse")
    public String showName();

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculate", targetNamespace = "http://service.fiap3esr.com.br/", className = "br.com.fiap3esr.stubclasses.Calculate")
    @ResponseWrapper(localName = "calculateResponse", targetNamespace = "http://service.fiap3esr.com.br/", className = "br.com.fiap3esr.stubclasses.CalculateResponse")
    @Action(input = "http://service.fiap3esr.com.br/Operation/calculateRequest", output = "http://service.fiap3esr.com.br/Operation/calculateResponse")
    public double calculate(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showOperator", targetNamespace = "http://service.fiap3esr.com.br/", className = "br.com.fiap3esr.stubclasses.ShowOperator")
    @ResponseWrapper(localName = "showOperatorResponse", targetNamespace = "http://service.fiap3esr.com.br/", className = "br.com.fiap3esr.stubclasses.ShowOperatorResponse")
    @Action(input = "http://service.fiap3esr.com.br/Operation/showOperatorRequest", output = "http://service.fiap3esr.com.br/Operation/showOperatorResponse")
    public String showOperator();

}
